/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.17.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Exercise { 
    description?: string | null;
    id: number;
    level?: string | null;
    owner_id: number;
    _public: boolean;
    solution_text?: string | null;
    task_text?: string | null;
    title: string;
}

