/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.17.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseInfo } from './exerciseInfo';


export interface ExerciseList { 
    items?: Array<ExerciseInfo>;
    length?: number;
    page?: number;
    pages?: number;
}

