/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.16.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LessonPageVariable } from './lessonPageVariable';


export interface LessonPageOption { 
    base_template_id?: number;
    note?: string;
    variables?: Array<LessonPageVariable> | null;
}

