/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.18.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LessonPageInfo } from './lessonPageInfo';
import { LessonPageElementStyle } from './lessonPageElementStyle';


export interface LessonPageElement { 
    content: string;
    id: number;
    lesson_page: LessonPageInfo;
    style: LessonPageElementStyle;
    type: string;
}

