/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.17.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LessonPageVariable } from './lessonPageVariable';
import { LessonPageElement } from './lessonPageElement';
import { LessonPageTemplate } from './lessonPageTemplate';


export interface LessonPage { 
    base_template?: LessonPageTemplate | null;
    elements?: Array<LessonPageElement>;
    id: number;
    note?: string | null;
    order: number;
    variables?: Array<LessonPageVariable>;
}

