/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.17.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PollSessionInfo } from './pollSessionInfo';
import { PollLabel } from './pollLabel';


export interface Poll { 
    id: number;
    labels: Array<PollLabel>;
    name: string;
    owner_id: number;
    sessions: Array<PollSessionInfo>;
}

